var HaruBanzuke = {
    rikishi: [
        {
            shikona: "Terunofuji",
            rank: "Yokozuna",
            direction: "East",
            wins: 3,
            losses: 3,
            absences: 9,
        },
        {
            shikona: "Shodai",
            rank: "Ozeki",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Takakeisho",
            rank: "Ozeki",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Mitakeumi",
            rank: "Ozeki",
            direction: "West",
            wins: 11,
            losses: 4,
            absences: 0,
        },
        {
            shikona: "Wakatakakage",
            rank: "Sekiwake",
            direction: "East",
            wins: 12,
            losses: 3,
            absences: 0,
        },
        {
            shikona: "Abi",
            rank: "Sekiwake",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Takanosho",
            rank: "Komusubi",
            direction: "East",
            wins: 4,
            losses: 11,
            absences: 0,
        },
        {
            shikona: "Hoshoryu",
            rank: "Komusubi",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Daieisho",
            rank: "Maegashira 1",
            direction: "East",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Ura",
            rank: "Maegashira 1",
            direction: "West",
            wins: 4,
            losses: 11,
            absences: 0,
        },
        {
            shikona: "Ichinojo",
            rank: "Maegashira 2",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Tamawashi",
            rank: "Maegashira 2",
            direction: "West",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Onosho",
            rank: "Maegashira 3",
            direction: "East",
            wins: 6,
            losses: 9,
            absences: 0,
        },
        {
            shikona: "Meisei",
            rank: "Maegashira 3",
            direction: "West",
            wins: 1,
            losses: 14,
            absences: 0,
        },
        {
            shikona: "Kiribayama",
            rank: "Maegashira 4",
            direction: "East",
            wins: 10,
            losses: 5,
            absences: 0,
        },
        {
            shikona: "Endo",
            rank: "Maegashira 4",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Ishiura",
            rank: "Maegashira 5",
            direction: "West",
            wins: 2,
            losses: 7,
            absences: 6,
        },
        {
            shikona: "Takarafuji",
            rank: "Maegashira 5",
            direction: "East",
            wins: 6,
            losses: 9,
            absences: 0,
        },
        {
            shikona: "Hokutofuji",
            rank: "Maegashira 6",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Kotonowaka",
            rank: "Maegashira 6",
            direction: "West",
            wins: 11,
            losses: 4,
            absences: 0,
        },
        {
            shikona: "Takayasu",
            rank: "Maegashira 7",
            direction: "East",
            wins: 12,
            losses: 3,
            absences: 0,
        },
        {
            shikona: "Okinoumi",
            rank: "Maegashira 7",
            direction: "West",
            wins: 5,
            losses: 10,
            absences: 0,
        },
        {
            shikona: "Chiyoshoma",
            rank: "Maegashira 8",
            direction: "East",
            wins: 5,
            losses: 10,
            absences: 0,
        },
        {
            shikona: "Sadanoumi",
            rank: "Maegashira 8",
            direction: "West",
            wins: 5,
            losses: 10,
            absences: 0,
        },
        {
            shikona: "Tobizaru",
            rank: "Maegashira 9",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Wakamotoharu",
            rank: "Maegashira 9",
            direction: "West",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Shimanoumi",
            rank: "Maegashira 10",
            direction: "East",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Aoiyama",
            rank: "Maegashira 10",
            direction: "West",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Myogiryu",
            rank: "Maegashira 11",
            direction: "East",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Terutsuyoshi",
            rank: "Maegashira 11",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
        {
            shikona: "Kotoeko",
            rank: "Maegashira 12",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Chiyotairyu",
            rank: "Maegashira 12",
            direction: "West",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Chiyomaru",
            rank: "Maegashira 13",
            direction: "East",
            wins: 5,
            losses: 10,
            absences: 0,
        },
        {
            shikona: "Chiyonokuni",
            rank: "Maegashira 13",
            direction: "West",
            wins: 5,
            losses: 6,
            absences: 4,
        },
        {
            shikona: "Kotoshoho",
            rank: "Maegashira 14",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Yutakayama",
            rank: "Maegashira 14",
            direction: "West",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Akua",
            rank: "Maegashira 15",
            direction: "East",
            wins: 4,
            losses: 11,
            absences: 0,
        },
        {
            shikona: "Tochinoshin",
            rank: "Mageashira 15",
            direction: "West",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Nishikigi",
            rank: "Maegashira 16",
            direction: "East",
            wins: 9,
            losses: 6,
            absences: 0,
        },
        {
            shikona: "Kotokuzan",
            rank: "Maegashira 16",
            direction: "West",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Kagayaki",
            rank: "Maegashira 17",
            direction: "East",
            wins: 7,
            losses: 8,
            absences: 0,
        },
        {
            shikona: "Ichiyamamoto",
            rank: "Maegashira 17",
            direction: "West",
            wins: 8,
            losses: 7,
            absences: 0,
        },
    ]
}
for(const wrestler of HaruBanzuke.rikishi){
    if(wrestler.rank === "Ozeki"){
        console.log(wrestler)
    }
}
